@baseURl = http://localhost:8000/api/v1/tasks

### Post Method
POST {{baseURl}}
Content-Type: application/json



### Get Method
GET {{baseURl}}
       

### Put Method
PATCH  {{baseURl}}
Content-Type: application/json

{
    "id":2,
    "type": "bad"
}



### Delete Method
DELETE {{baseURl}}
Content-Type: application/json



