@baseURl = http://localhost:8000/api/v1/tasks

### Post Method
POST {{baseURl}}
Content-Type: application/json

{
"fName":"Bishes",
"lName":"Adhikari"
}


### Get Method
GET {{baseURl}}
       

### Put Method 
PATCH  {{baseURl}}
Content-Type: application/json

{
    "id":2,
    "type": "bad"
}



### Delete Method
DELETE {{baseURl}}/3
Content-Type: application/json



