@baseURl = http://localhost:8000/api/v1/tasks

### Post Method
POST {{baseURl}}
Content-Type: application/json

{
    "task": "coding",
    "hours": 50
}

### Get Method
GET {{baseURl}}
       

### Put Method
PUT {{baseURl}}
Content-Type: application/json



### Delete Method
DELETE {{baseURl}}
Content-Type: application/json